// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNSVmHoyFKPbww34HWr2YSv4HDl1b6e8',
    appId: '1:93409583405:web:ec190e0306a925cf5e33a4',
    messagingSenderId: '93409583405',
    projectId: 'csc-4360-activity-13',
    authDomain: 'csc-4360-activity-13.firebaseapp.com',
    storageBucket: 'csc-4360-activity-13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ncGzkL6e0-uyc6z0RBZ_PILRLpbLKr4',
    appId: '1:93409583405:android:ae0e140ea35288a05e33a4',
    messagingSenderId: '93409583405',
    projectId: 'csc-4360-activity-13',
    storageBucket: 'csc-4360-activity-13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQB9wQxaY1POG47A4716QfVNRMPX8wVC8',
    appId: '1:93409583405:ios:31c372cbd154ffd75e33a4',
    messagingSenderId: '93409583405',
    projectId: 'csc-4360-activity-13',
    storageBucket: 'csc-4360-activity-13.firebasestorage.app',
    iosBundleId: 'com.example.activity13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQB9wQxaY1POG47A4716QfVNRMPX8wVC8',
    appId: '1:93409583405:ios:31c372cbd154ffd75e33a4',
    messagingSenderId: '93409583405',
    projectId: 'csc-4360-activity-13',
    storageBucket: 'csc-4360-activity-13.firebasestorage.app',
    iosBundleId: 'com.example.activity13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwNSVmHoyFKPbww34HWr2YSv4HDl1b6e8',
    appId: '1:93409583405:web:b9230daca307a4ed5e33a4',
    messagingSenderId: '93409583405',
    projectId: 'csc-4360-activity-13',
    authDomain: 'csc-4360-activity-13.firebaseapp.com',
    storageBucket: 'csc-4360-activity-13.firebasestorage.app',
  );
}
